### ISSUE TITLE
Setting up OpenSpiel

### ISSUE THREAD

**Issue by vrn25** [manish-pra/copg#2] opened 2020-11-06 15:21 UTC
Hi @manish-pra , I have been trying to setup OpenSpiel on a cluster on which I do not have root access. In your copg implementation, you have used markov soccer environment from OpenSpiel. Have you tried getting it to work on a cluster without sudo privileges? For more details about the problem, please refer the following issue - https://github.com/deepmind/open_spiel/issues/436. Please check the comments till the end as some of the beginning and intermediate errors were solved.

**Comment by lanctot** [comment] 2020-11-06 15:52
@manish-pra side note, your work this seems quite interesting! I encourage you to submit an edited version of your paper to submit to our workshop [AAAI  Reinforcement Learning in Games](http://aaai-rlg.mlanctot.info/) -- due date is this Monday Nov 9th. We explicitly allow submissions that have been already submitted to a conference and even accepted. :)

(Sorry for the shameless plug!)

**Comment by manish-pra** [comment] 2020-11-11 14:01
@lanctot  Thanks for the suggestion. The workshop is quite relevant to me. I somehow missed this notification and looks like the deadline is over now. If there is any other way to participate, let me know i will be interested.

@vrn25 Looks like the problem is solved by now. Thanks for asking.

**Closed as completed** 2020-11-12 16:11 UTC
